### ISSUE TITLE
Inconsistent render behavior when fetch rejects with net::ERR_SSL_PROTOCOL_ERROR

### ISSUE THREAD

**Issue by jgensler8** [contiamo/restful-react#78] opened 2018-10-26 16:28 UTC
**Describe the bug**

The fetch api can reject its returned promise if the server it is fetching data from returns an invalid certificate. While this behavior should result in the `<Get>` rendering it's `error` section, I instead see the progress indicator. While not 100% sure, I believe this is caused by the following line: https://github.com/contiamo/restful-react/blob/v5.2.1/src/Get.tsx#L202 as I figured there was some `await` call without a `catch`.

**To Reproduce**

Option 1:

If this ends up sharing correctly, this should be located here: https://codesandbox.io/s/9p3wmx7po

Option 2:

If using react-scripts, you should be able to switch some api call from `http://...` to `https://...`.

```
<RestfulProvider base="https://localhost:8080">
<Get path="/some/api/pets">
{(pets, { loading, error }) =>
    loading ? (
       Loading...
    ) : (
        <div>
        You should only see this after things are loaded.
        {error ? (
            <div>"OH NO!"</div>
        ) : (
            <div>success!</div>
        )}
        </div>
)}
</Get>
</RestfulProvider>
```

Option 3:

1. Create a server that returns a different certificate than the domain used to query it (Subject Alternative Name or Common Name is different)
2. Send a GET request to this server
3. observe UI behavior

**Expected behavior**

If the GET request fails because in invalid certificates, the `error` section should render.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: OSX Darwin Kernel Version 15.6.0
 - Browser Chrome
 - Version `v5.2.1`

**Additional context**

There might be other edge cases (maybe CORS or timeouts?) that cause this same behavior though I don't have any evidence of that.

**Comment by TejasQ** [comment] 2018-10-29 11:04
Thanks for the report! Would you like to pair up on a PR? 😄

**Comment by jgensler8** [comment] 2018-10-29 23:51
I should be able to find some time this week to work on a PR.

I started by trying to run the test suite (`npm test`). I had a few errors and I want to make sure that I can easily test the changes on my laptop before developing.

First, I got the following:

```
 FAIL  src/Poll.test.tsx
  ● Test suite failed to run

    TypeScript diagnostics (customize using `[jest-config].globals.ts-jest.diagnostics` option):
    src/Poll.test.tsx:419:23 - error TS7006: Parameter 'data' implicitly has an 'any' type.

    419       const resolve = data => ({ ...data, too: "bar" });
                              ~~~~
    src/Poll.test.tsx:420:26 - error TS7006: Parameter 'data' implicitly has an 'any' type.

    420       const newResolve = data => ({ ...data, foo: "bar" });
                                 ~~~~

 FAIL  src/Mutate.test.tsx
  ● Test suite failed to run

    TypeScript diagnostics (customize using `[jest-config].globals.ts-jest.diagnostics` option):
    src/Mutate.test.tsx:192:48 - error TS7006: Parameter 'error' implicitly has an 'any' type.

    192       return children.mock.calls[0][0]().catch(error => {
                                                       ~~~~~

 FAIL  src/Get.test.tsx
  ● Test suite failed to run

    TypeScript diagnostics (customize using `[jest-config].globals.ts-jest.diagnostics` option):
    src/Get.test.tsx:512:23 - error TS7006: Parameter 'a' implicitly has an 'any' type.

    512       const resolve = a => a;
                              ~
    src/Get.test.tsx:550:23 - error TS7006: Parameter 'a' implicitly has an 'any' type.

    550       const resolve = a => a;
                              ~
    src/Get.test.tsx:574:23 - error TS7006: Parameter 'a' implicitly has an 'any' type.

    574       const resolve = a => a;
                              ~
    src/Get.test.tsx:605:23 - error TS7006: Parameter 'a' implicitly has an 'any' type.

    605       const resolve = a => a;
                              ~
    src/Get.test.tsx:630:31 - error TS7006: Parameter 'a' implicitly has an 'any' type.

    630       const providerResolve = a => a;
                                      ~
    src/Get.test.tsx:637:26 - error TS7006: Parameter 'a' implicitly has an 'any' type.

    637       const newResolve = a => a;
                                 ~
```

After tidying up those errors, I got the following:
```
 FAIL  src/Get.test.tsx
  ● Test suite failed to run

    TypeScript diagnostics (customize using `[jest-config].globals.ts-jest.diagnostics` option):
    src/Mutate.tsx:127:46 - error TS2345: Argument of type '{ headers: { "content-type": string; } | { append(name: string, value: string): void; delete(name: string): void; get(name: string): string | null; has(name: string): boolean; set(name: string, value: string): void; forEach(callbackfn: (value: string, key: string, parent: Headers) => void, thisArg?: any): void; "con...' is not assignable to parameter of type 'RequestInit | undefined'.
      Type '{ headers: { "content-type": string; } | { append(name: string, value: string): void; delete(name: string): void; get(name: string): string | null; has(name: string): boolean; set(name: string, value: string): void; forEach(callbackfn: (value: string, key: string, parent: Headers) => void, thisArg?: any): void; "con...' is not assignable to type 'RequestInit'.
        Types of property 'body' are incompatible.
          Type '{} | undefined' is not assignable to type 'string | Blob | ArrayBufferView | ArrayBuffer | FormData | URLSearchParams | ReadableStream | null | undefined'.
            Type '{}' is not assignable to type 'string | Blob | ArrayBufferView | ArrayBuffer | FormData | URLSearchParams | ReadableStream | null | undefined'.
              Type '{}' is not assignable to type 'ReadableStream'.
                Property 'locked' is missing in type '{}'.

    127     const request = new Request(requestPath, {
                                                     ~
    128       method: verb,
        ~~~~~~~~~~~~~~~~~~~
    ...
    138       },
        ~~~~~~~~
    139     });
        ~~~~~
```

which is a result of this line:  https://github.com/contiamo/restful-react/blob/431abc5b3bf47ea4deac90a305407450b40eb416/src/Mutate.tsx#L129

@TejasQ have you seen these errors before? Maybe I am using a older version of the testing libraries? Do you know if the TravisCI build is passing for latest commits to master?

```
$ npm test

> restful-react@5.2.1 test /private/tmp/restful-react
> operational-scripts test

ts-jest[backports] (WARN) "[jest-config].globals.ts-jest.tsConfigFile" is deprecated, use "[jest-config].globals.ts-jest.tsConfig" instead.
ts-jest[backports] (WARN) Your Jest configuration is outdated. Use the CLI to help migrating it: ts-jest config:migrate <config-file>.
```

**Comment by TejasQ** [comment] 2018-10-30 13:32
@jgensler8, that's a little strange. Here's my output from `npm test` on `master`:

![image](https://user-images.githubusercontent.com/9947422/47721334-2caf9900-dc50-11e8-9716-1d529bee8279.png)

Ah! Good catch! I have discovered the issues _after_ cleaning out my `node_modules` and treating the project as a fresh clone. I'll fix up some things and get back to you. Thank you for letting us know about this!

**Comment by TejasQ** [comment] 2018-10-30 14:17
^ fixes the tests. 😄

**Comment by TejasQ** [comment] 2018-10-30 14:19
![](https://github.trello.services/images/mini-trello-icon.png) [Inconsistent render behavior when fetch rejects with net::ERR_SSL_PROTOCOL_ERROR](https://trello.com/c/4NhNu50G/549-inconsistent-render-behavior-when-fetch-rejects-with-neterrsslprotocolerror)

**Comment by TejasQ** [comment] 2018-10-30 15:04
Accidentally closed that. Oops!

SO, @jgensler8, `yarn add @operational/scripts@latest -D` will fix the test runner. 😄 Can you confirm it does? If it does, you should be good to go! 🚀

**Comment by jgensler8** [comment] 2018-10-30 19:53
I am now able to generate the same output as you have:

```
$ npm test

> restful-react@5.2.1 test /private/tmp/restful-react
> operational-scripts test

 PASS  src/util/composeUrl.test.ts
 PASS  src/Mutate.test.tsx (5.513s)
 PASS  src/Get.test.tsx (6.162s)
  ● Console

    console.error node_modules/react-dom/cjs/react-dom.development.js:520
      Warning: Can't call setState (or forceUpdate) on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.
          in ContextlessGet (created by Context.Consumer)
          in RestfulReactProvider (created by Context.Consumer)
          in Get
          in RestfulReactProvider

 PASS  src/Poll.test.tsx (8.756s)

Test Suites: 4 passed, 4 total
Tests:       79 passed, 79 total
Snapshots:   0 total
Time:        11.023s
Ran all test suites.
```

I have also tried deleting and cloning the repo and I think the problem should be fixed for other developers.

**Comment by TejasQ** [comment] 2018-10-31 08:48
Perfect! We have an open PR that fixes the warning.

**Comment by fabien0102** [comment] 2018-12-13 21:14
@jgensler8 I'm not able to reproduce the error with the version `7.1.0`, can you confirm on your side that your bug is really resolve?

**Comment by jgensler8** [comment] 2018-12-13 21:43
Looks like the the render does work with `7.1.0`. However, it appears that bad certs aren't considered an "error." (this is totally up to you to decide this behavior). Here is an updated sandbox: https://codesandbox.io/s/w6xyyj2nw

**Comment by fabien0102** [comment] 2018-12-13 21:51
If it's a 200 and the content is available without error, I don't really see the point to handle this as an error.
For now I think it's should be ok like this, I've added a real try/catch on `fetch` in #97 for network error so it should be more reliable 😃 

I will close this issue for now, if you have any edge case where we have an error or anything that are not caught correctly, please open a new issue.

Thanks for the reporting and your reactivity, it's really appreciate 💯

**Closed by fabien0102** 2018-12-13 21:51 UTC
