### ISSUE TITLE
Respect full URLs even if using a provider

### ISSUE THREAD

**Issue by kallaspriit** [contiamo/restful-react#98] opened 2019-01-30 09:05 UTC
If I do use a `<RestfulProvider base="https://example.com/api">` but then make a request using full URL (`https://example.com/api/xxx` etc), it should use the provided URL not concatenate them together.

Right now this 

```typescript
<RestfulProvider base="https://example.com/api">
  <Get path="https://reqres.in/api/users">
    ...
  </Get>
</RestfulProvider>
```

Results in attempting to fetch URL `https://example.com/apihttps://reqres.in/api/users` but it should just use the provided URL `https://reqres.in/api/users`.

Makes sense that most of my requests go to my own API for which I have added the `RestfulProvider` but perhaps I want to make some requests to 3rd party API so for those requests, I would provide the full URL and expect the provider base to be ignored.

Tested on React native but it's likely the same on the web.

**Comment by TejasQ** [comment] 2019-01-30 09:36
@kallaspriit, that's actually the expected behavior. If you'd like to make a request to another host, we recommend using the `base` prop on `Get` instead of `path` since including a protocol is not really a `path`.

**Comment by kallaspriit** [comment] 2019-01-30 09:46
In the very first example of the library a full URL including the protocol is used in `path` so it's a bit confusing as to why the same thing wouldn't work inside a provider.

```typescript
import React from "react";
import Get from "restful-react";

const MyComponent = () => (
  <Get path="https://dog.ceo/api/breeds/image/random">
    {randomDogImage => <img alt="Here's a good boye!" src={randomDogImage && randomDogImage.message} />}
  </Get>
);

export default MyComponent;
```

If this is still the expected behavior then I guess it could be documented how to make requests to another host inside a provider.

**Comment by TejasQ** [comment] 2019-01-30 09:50
Thank you for pointing that out, @kallaspriit! Notice how `Get` isn't used in a `RestfulProvider` though. That's why we use `path`. We can update the example. Would you like to open a PR?

**Comment by kallaspriit** [comment] 2019-01-30 10:08
I guess You could just add a short section under the provider description that do make a request to another host, `base` should be set instead of `path` with a similar example as your initial comment.

Right now the docs don't directly mention that `<Get>` even accepts a `base` attribute.

Also the highlight link range does not cover all parameters :)
https://github.com/contiamo/restful-react/blob/master/src/Get.tsx#L50-L87

**Comment by TejasQ** [comment] 2019-01-30 10:13
Yup. Would you like to open a PR?

**Comment by kallaspriit** [comment] 2019-01-30 10:49
I'm pretty busy right now, got a deadline to meet. It would be easier for You to do the simple docs update directly?

**Comment by TejasQ** [comment] 2019-01-30 12:09
Got it. I'll do it. Just wanted to give you the opportunity to contribute. 🙂

**Comment by TejasQ** [comment] 2019-10-28 10:41
We want to move to a hooks API, so closing this for now.

**Closed by TejasQ** 2019-10-28 10:41 UTC
